services:
  claude-container:
    build: .
    user: "${UID:-1000}:${GID:-1000}"                    # run as you
    command: tail -f /dev/null                           # Keep container running
    environment:
      ALLOWED_DOMAINS: >-
        registry.npmjs.org,
        api.anthropic.com,
        sentry.io,
        statsig.anthropic.com,
        statsig.com
    volumes:
      - ./workspace:/workspace:rw                        # dedicated workspace folder, RW
      - ./.claude:/home/node/.claude:rw                  # persist Claude settings
      - ./.claude.json:/home/node/.claude.json:rw        # persist Claude settings
      - ./.history:/commandhistory:rw                    # persist shell history
    ports:
      - "5173:5173"                                      # dev server (change as needed)
      - "3000:3000"                                      # Next.js dev server
    tmpfs:
      - /tmp                                             # avoid writing to container FS
    read_only: false                                     # repo is already RW
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges
    pids_limit: 256

